export const theme = {
  bg:         "#0C0E14",
  surface:    "#13151E",
  border:     "#222536",
  text:       "#F0F2FF",
  textSub:    "#8892B0",
  textFaint:  "#3D4466",
  cyan:       "#38EFC8",
  violet:     "#B388FF",
  rose:       "#FF6B8A",
  amber:      "#FFCC5C",
  green:      "#4ADE80",
  fontDisplay:"'Outfit', sans-serif",
  fontBody:   "'DM Sans', sans-serif",
  fontMono:   "'Fira Code', monospace",
};